apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dockwork
  namespace: {{ .Values.namespace }}
  labels:
    app: dockwork
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      name: dockwork
  template:
    metadata:
      labels:
        name: dockwork
    spec:
      hostNetwork: true
      containers:
        - name: dockwork
          image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ if .Values.image.tag }}{{ .Values.image.tag }}{{ else }}{{ .Files.Get "version" }}{{ end }}
          volumeMounts:
            - name: containerdsock
              mountPath: /var/run/containerd/containerd.sock
              readOnly: true
            - name: hostdata
              mountPath: /hostdata/hostname
              readOnly: true
          env:
          - name: SERVICE_ENDPOINT
            value: {{ .Values.service }}
          - name: SERVICE_ENDPOINT_WS
            value: {{ .Values.websocketservice }}
      volumes:
        - name: containerdsock
          hostPath:
            path: /var/run/containerd/containerd.sock
        - name: hostdata
          hostPath:
            path: /etc/hostname